### PR TITLE
docs: reference the right repo in badges

### PR DESCRIPTION
**Pull request by dubzzz**
Fixing all the links that reference the wrong npm/github locations. Also dropping coverage badge as it seems not to apply anymore.

### CODE REVIEW

**Comment by dubzzz** [comment]
@Kikobeats I think there are still some broken references but I'm not sure they got migrated on your hand. Everything linked to Github Pages (github.io links) should probably also referenec new targets if any 🤔

**Comment by Kikobeats** [comment]
@dubzzz Thanks a lot!

Can you explain what refernces are still broken?

**Comment by dubzzz** [comment]
This one: https://mac-s-g.github.io/react-json-view/demo/dist/ still references the old project and so does not run against your package if I'm not wrong 🤔

**Comment by Kikobeats** [comment]
Fixed https://react-json-view.microlink.io/ 🎉

It's possible the demo source code should to be updated, can you take a look if evertyhing looks fine to you?

The demo source code is living at https://github.com/microlinkhq/react-json-view/tree/master/demo/src

**Comment by dubzzz** [comment]
I updated the few last references to the original repository. That said I kept the "My email address is listed on my [github user page](https://github.com/mac-s-g)." on the README as I did not know how to update it.

**Comment by Kikobeats** [comment]
I moved relevant information to CONTRIBUTING.md 🙂

**Pull request merged**
